### ISSUE TITLE
ObjectJob is always null

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#14]
When creating domains, the result, the ObjectJob, contains only null objects:

```
class ObjectJob {
    job: null
    object: null
    niccomLogs: null
    authentication: null
    dcvAuth: null
}
```

**Comment by Ephenodrom** [comment]
@andlinger 
I added a temporary fix for that. The problem was that the swagger documentation, that we provide was not correct for operations on domains and certificate that create an asynchronous job on our side. The returned object type was defined as JsonObjectJob but the API returns a Job object. Therefore the mapping did not work.

The problem only appeared in this SDK, because this is the only SDK that 100% relys on the swagger documentation.

Therefore, please update to 0.2.5 and once the swagger documentation is updated, i will create another release and change the temporary fix to a real fix.
