### ISSUE TITLE
Artifact on Maven Central

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#7]
The Maven build no longer works because the Git submodules have not been tagged and have changed.

Why aren't the artifacts being uploaded to Maven Central?

**Comment by Ephenodrom** [comment]
Hello @andlinger 
Please try the version 0.2.2. I fixed the small bug causing the the "mvn install" command to fail (#8).

The plan is to setup a selfhostet public maven repository and use this to ship this sdk in the future. 
Due to the current circumstances, realisation of the public repository is dragging on a bit.

We will update the README as soon as the public repository will be ready to use.
